"navigation":{
    "lists":[
         {
             "text":"HOME",
             "link":"/",
             "target":"_self"
         },
         {
             "text":"SCHEDULE",
             "link":"/schedule",
             "target":"_self"
         },
         {
             "text":"TEAMS",
             "link":"/teams",
             "target":"_self"
         },
         {
             "text":"STATS",
             "link":"/stats",
             "target":"_self"
         },
         {
             "text":"ABOUT",
             "link":"about",
             "target":"_self"
         }
     ]
 }